name: cytalia
favicon: null
layout_spectrum: 0.35959536605514586
typography_spectrum: 0.9050903231836855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6875
  lightness: 0.015496737556532025
  saturation: 0.15596254798583686
  rhythmicContrast: 0.862922437954694
purpose: []
